Feature Engineering 
- Feature Transformation
  1. Missing value imputation
  2. Handling categorical features
  3. Outlier Detection
  4. Feautre Scaling 
- Feature Consturction
  1. From given feaure we manually create new features
  2. Feature Splitting
- Feature Selection
- Feature Extraction

Feature Consturction
- it is a very special thing in ML it is manual where we create feautres manually. In this process we create features manually

Feature Splitting
- tidy data hudena kaile kai so we have to split the data in single cell there is more than one data then what we do is feature splitting

In [14]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
import seaborn as sns

In [36]:
df = pd.read_csv('train.csv',usecols=["Age","Pclass","SibSp","Parch","Survived"])

In [38]:
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [41]:
df.dropna(inplace=True)

In [47]:
X = df.iloc[: , 1:5]

In [49]:
X

     Pclass   Age  SibSp  Parch
0         3  22.0      1      0
1         1  38.0      1      0
2         3  26.0      0      0
3         1  35.0      1      0
4         3  35.0      0      0
..      ...   ...    ...    ...
885       3  39.0      0      5
886       2  27.0      0      0
887       1  19.0      0      0
889       1  26.0      0      0
890       3  32.0      0      0

[714 rows x 4 columns]

In [57]:
y = df.iloc[:,0]

In [59]:
y

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: Survived, Length: 714, dtype: int64

In [61]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring="accuracy",cv=20))

0.6933333333333332

## Applying Feature Construction

In [64]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1

In [66]:
X.head()

   Pclass   Age  SibSp  Parch  Family_size
0       3  22.0      1      0            2
1       1  38.0      1      0            2
2       3  26.0      0      0            1
3       1  35.0      1      0            2
4       3  35.0      0      0            1

In [68]:

def myfunc(num):
    if num == 1:
        #alone
        return 0
    elif num >1 and num <=4:
        # small family
        return 1
    else:
        # large family
        return 2

In [70]:

X['Family_type'] = X['Family_size'].apply(myfunc)

In [72]:

X.head()

   Pclass   Age  SibSp  Parch  Family_size  Family_type
0       3  22.0      1      0            2            1
1       1  38.0      1      0            2            1
2       3  26.0      0      0            1            0
3       1  35.0      1      0            2            1
4       3  35.0      0      0            1            0

In [74]:

X.drop(columns=['SibSp','Parch','Family_size'],inplace=True)

In [76]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

0.7003174603174602

## Feature Splitting

In [119]:

df = pd.read_csv('train.csv')

In [121]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [123]:

t = df['Name'].str.split(', ', expand=True)
t

             0                                           1
0       Braund                             Mr. Owen Harris
1      Cumings  Mrs. John Bradley (Florence Briggs Thayer)
2    Heikkinen                                 Miss. Laina
3     Futrelle          Mrs. Jacques Heath (Lily May Peel)
4        Allen                           Mr. William Henry
..         ...                                         ...
886   Montvila                                 Rev. Juozas
887     Graham                        Miss. Margaret Edith
888   Johnston              Miss. Catherine Helen "Carrie"
889       Behr                             Mr. Karl Howell
890     Dooley                                 Mr. Patrick

[891 rows x 2 columns]

In [125]:
t[1].str.split('.', expand=True)[0]

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
886     Rev
887    Miss
888    Miss
889      Mr
890      Mr
Name: 0, Length: 891, dtype: object

In [127]:
df['Title'] = df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

In [129]:

df[['Title','Name']]

    Title                                               Name
0      Mr                            Braund, Mr. Owen Harris
1     Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    Miss                             Heikkinen, Miss. Laina
3     Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4      Mr                           Allen, Mr. William Henry
..    ...                                                ...
886   Rev                              Montvila, Rev. Juozas
887  Miss                       Graham, Miss. Margaret Edith
888  Miss           Johnston, Miss. Catherine Helen "Carrie"
889    Mr                              Behr, Mr. Karl Howell
890    Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]